export const ruleValidate = (obj) => {
  const rule = {
    inwellTime: [{
      required: true,
      message: "入井时间不能为空",
      trigger: "blur,change",
    },],
    outwellTime: [{
      required: true,
      message: "出井时间不能为空",
      trigger: "blur,change",
    },
    ],
    shiftTimeQuantumId: [{
      type: 'number',
      required: true,
      message: "时间段不能为空",
      trigger: "blur,change",
    },],
    inwellStationNo: [{
      required: true,
      message: "入井基站不能为空",
      trigger: "blur,change",
    },],
    outwellStationNo: [{
      required: true,
      message: "出井基站不能为空",
      trigger: "blur,change",
    },],
    stationNo: [{
      required: true,
      message: "出井基站不能为空",
      trigger: "blur,change",
    },],
    stationDirection: [{
      type: 'number',
      required: true,
      message: "方向不能为空",
      trigger: "blur,change",
    },],
    stationDistance: [{
      required: true,
      message: "距离不能为空",
      trigger: "blur,change",
    },],
  }
  return rule;
}
export const originForm = {
  att: {
    shiftTimeQuantumId: "",
    shiftTimeQuantumName: "",
    inwellTime: "",
    inwellStationNo: "",
    inwellStationName: "",
    outwellTime: "",
    outwellStationNo: "",
    outwellStationName: "",
    dataType: 1,
    objectNo: '',
    shiftDate: '',
    shiftId: '',
    shiftName: '',
    cnName: '',
    spellName: '',
    cardNo: '',
    positionId: '',
    positionNo: '',
    positionName: '',
    dutyId: '',
    dutyNo: '',
    dutyName: '',
    deptId: '',
    deptName: '',
    isDutyLeader: '',
    isWithLeader: '',
    isMineLeader: '',
    isSpeicial: '',
    workStatus: '',
    countClassMethod: '',
    is_origin: true,
    list: [],
    inStationItem: {},
    outStationItem: {}
  },
  track: {
    stationNo: "",
    mainStationHid: "",
    stationDirection: "",
    stationDistance: "",
    dataTime: "",
    stationName: "",
    tunnelNo: "",
    tunnelName: "",
    tunnelLoc: "",
  },
  inStationItem: {
    stationNo: "",
    dataTime: "",
    stationDirection: "",
    stationDistance: "",
    mainStationHid: "",
    stationName: "",
    tunnelNo: "",
    tunnelName: "",
    tunnelLoc: "",
  },
  outStationItem: {
    stationNo: "",
    dataTime: "",
    stationDirection: "",
    stationDistance: "",
    mainStationHid: "",
    stationName: "",
    tunnelNo: "",
    tunnelName: "",
    tunnelLoc: "",
  },
}
export const initForm = {
  cardNo: "",
  date: "",
  // 轨迹参数
  inStationItem: {
    stationNo: "",
    dataTime: "",
    stationDirection: "",
    stationDistance: "",
    mainStationHid: "",
    stationName: "",
    tunnelNo: "",
    tunnelName: "",
    tunnelLoc: "",
  },
  outStationItem: {
    stationNo: "",
    dataTime: "",
    stationDirection: "",
    stationDistance: "",
    mainStationHid: "",
    stationName: "",
    tunnelNo: "",
    tunnelName: "",
    tunnelLoc: "",
  },
  attendance: [{
    shiftTimeQuantumId: "",
    shiftTimeQuantumName: "",
    inwellTime: "",
    inwellStationNo: "",
    inwellStationName: "",
    outwellTime: "",
    outwellStationNo: "",
    outwellStationName: "",
    dataType: 1,
    // 固定字段
    objectNo: '',
    shiftDate: '',
    shiftId: '',
    shiftName: '',
    cnName: '',
    spellName: '',
    cardNo: '',
    positionId: '',
    positionNo: '',
    positionName: '',
    dutyId: '',
    dutyNo: '',
    dutyName: '',
    deptId: '',
    deptName: '',
    isDutyLeader: '',
    isWithLeader: '',
    isMineLeader: '',
    isSpeicial: '',
    workStatus: '',
    countClassMethod: '',
    is_origin: true,
    // 轨迹信息
    list: [],
    inStationItem: {},
    outStationItem: {}
  },], //出勤记录
  trackList: [{
    stationNo: "",
    mainStationHid: "",
    stationDirection: "",
    stationDistance: "",
    dataTime: "",
    stationName: "",
    tunnelNo: "",
    tunnelName: "",
    tunnelLoc: "",
  },], //轨迹信息
}