export default {
    menuTree: [
        {
            code: "0001",
            icon: "ios-add-circle",
            label: "iview篇章",
            parent: "",
            url: "/",
        },
        {
            code: "0001-01",
            label: "Table",
            parent: "0001",
            url: "/table",
        },
        {
            code: "0001-02",
            label: "表单动态校验",
            parent: "0001",
            url: "/table/dynamicForm",
        },
        {
            code: "0002",
            icon: "ios-add-circle",
            label: "预处理器sass",
            parent: "",
            url: "/",
        },
        {
            code: "0002-01",
            icon: "ios-add-circle",
            label: "颜色函数",
            parent: "0002",
            url: "/sassColor",
        },
        {
            code: "0003",
            icon: "ios-add-circle",
            label: "页面布局",
            parent: "",
            url: "/",
        },
        {
            code: "0003-01",
            icon: "ios-add-circle",
            label: "瀑布流布局",
            parent: "0003",
            url: "/layIndex",
        },
        {
            code: "0003-02",
            icon: "ios-add-circle",
            label: "文件导出",
            parent: "0003",
            url: "/exportFile",
        },
        {
            code: "0003-03",
            icon: "ios-add-circle",
            label: "loading动画",
            parent: "0003",
            url: "/loading",
        },
        {
            code: "0004",
            icon: "ios-add-circle",
            label: "自定义组件",
            parent: "",
            url: "/",
        },
        {
            code: "0004-01",
            icon: "ios-add-circle",
            label: "下拉框",
            parent: "0004",
            url: "/custom/dropItem",
        },
        {
            code: "0005",
            icon: "ios-add-circle",
            label: "事件优化",
            parent: "",
            url: "/",
        },
        {
            code: "0005-01",
            icon: "ios-add-circle",
            label: "节流和防抖",
            parent: "0005",
            url: "/event/throttle",
        },
        {
            code: "0006",
            icon: "ios-add-circle",
            label: "Vue基础",
            parent: "",
            url: "/",
        },
        {
            code: "0006-01",
            icon: "ios-add-circle",
            label: "created+mounted",
            parent: "0006",
            url: "/base/cAndM",
        },
        {
            code: "0006-02",
            icon: "ios-add-circle",
            label: ".sync修饰符",
            parent: "0006",
            url: "/base/sync",
        },
        {
            code: "0006-03",
            icon: "ios-add-circle",
            label: "父组件与子组件执行顺序",
            parent: "0006",
            url: "/base/childAp",
        },
        {
            code: "0006-04",
            icon: "ios-add-circle",
            label: "slot插槽",
            parent: "0006",
            url: "/base/slot",
        },
        {
            code: "0007",
            icon: "ios-add-circle",
            label: "饿了么ui篇章",
            parent: "",
            url: "/",
        },
        {
            code: "0007-01",
            icon: "ios-add-circle",
            label: "二次封装表单",
            parent: "0007",
            url: "/eleUi/reForm",
        },
        {
            code: "0008",
            icon: "ios-add-circle",
            label: "原生js+",
            parent: "",
            url: "/",
        },
        {
            code: "0008-01",
            icon: "ios-add-circle",
            label: "事件循环机制",
            parent: "0008",
            url: "/js/index",
        },
        {
            code: "0008-02",
            icon: "ios-add-circle",
            label: "闭包",
            parent: "0008",
            url: "/js/closure",
        },
    ]
}