console.log(process)
// process {
//     version: 'v14.16.0',
//     versions: {
//       node: '14.16.0',
//       v8: '8.4.371.19-node.18',
//       uv: '1.40.0',
//       zlib: '1.2.11',
//       brotli: '1.0.9',
//       ares: '1.16.1',
//       modules: '83',
//       nghttp2: '1.41.0',
//       napi: '7',
//       llhttp: '2.1.3',
//       openssl: '1.1.1j',
//       cldr: '37.0',
//       icu: '67.1',
//       tz: '2020a',
//       unicode: '13.0'
//     },
//     arch: 'x64',
//     platform: 'win32',
//     release: {
//       name: 'node',
//       lts: 'Fermium',
//       sourceUrl: 'https://nodejs.org/download/release/v14.16.0/node-v14.16.0.tar.gz',
//       headersUrl: 'https://nodejs.org/download/release/v14.16.0/node-v14.16.0-headers.tar.gz',
//       libUrl: 'https://nodejs.org/download/release/v14.16.0/win-x64/node.lib'
//     },
//     _rawDebug: [Function: _rawDebug],
//     moduleLoadList: [
//       'Internal Binding native_module',
//       'Internal Binding errors',
//       'NativeModule internal/errors',
//       'Internal Binding config',
//       'Internal Binding constants',
//       'Internal Binding util',
//       'Internal Binding types',
//       'NativeModule internal/util',
//       'NativeModule internal/util/types',
//       'NativeModule internal/assert',
//       'Internal Binding icu',
//       'NativeModule internal/util/inspect',
//       'NativeModule events',
//       'Internal Binding buffer',
//       'Internal Binding string_decoder',
//       'NativeModule internal/validators',
//       'NativeModule internal/buffer',
//       'NativeModule buffer',
//       'Internal Binding symbols',
//       'Internal Binding messaging',
//       'NativeModule internal/worker/js_transferable',
//       'NativeModule internal/process/per_thread',
//       'Internal Binding process_methods',
//       'Internal Binding credentials',
//       'Internal Binding async_wrap',
//       'Internal Binding task_queue',
//       'NativeModule internal/async_hooks',
//       'NativeModule internal/process/promises',
//       'NativeModule internal/fixed_queue',
//       'NativeModule internal/process/task_queues',
//       'Internal Binding trace_events',
//       'NativeModule internal/constants',
//       'NativeModule internal/console/constructor',
//       'NativeModule internal/console/global',
//       'NativeModule internal/util/inspector',
//       'Internal Binding inspector',
//       'NativeModule internal/querystring',
//       'NativeModule path',
//       'Internal Binding url',
//       'NativeModule internal/url',
//       'NativeModule internal/encoding',
//       'Internal Binding timers',
//       'NativeModule internal/linkedlist',
//       'NativeModule internal/priority_queue',
//       'NativeModule internal/util/debuglog',
//       'NativeModule internal/timers',
//       'NativeModule timers',
//       'NativeModule internal/process/execution',
//       'NativeModule internal/process/warning',
//       'NativeModule internal/process/signal',
//       'Internal Binding options',
//       'NativeModule internal/options',
//       'NativeModule internal/bootstrap/pre_execution',
//       'NativeModule internal/inspector_async_hook',
//       'Internal Binding report',
//       'NativeModule internal/process/report',
//       'Internal Binding fs',
//       'NativeModule internal/fs/utils',
//       'Internal Binding fs_dir',
//       'NativeModule internal/fs/dir',
//       'NativeModule fs',
//       'NativeModule internal/idna',
//       'NativeModule url',
//       'NativeModule internal/modules/cjs/helpers',
//       'NativeModule internal/source_map/source_map_cache',
//       'Internal Binding contextify',
//       'NativeModule vm',
//       'NativeModule internal/modules/package_json_reader',
//       'Internal Binding module_wrap',
//       'NativeModule internal/modules/esm/module_job',
//       'NativeModule internal/modules/esm/module_map',
//       'NativeModule internal/modules/esm/resolve',
//       'NativeModule internal/modules/esm/get_format',
//       'NativeModule internal/fs/rimraf',
//       'NativeModule internal/fs/promises',
//       'NativeModule internal/modules/esm/get_source',
//       'NativeModule internal/modules/esm/transform_source',
//       'NativeModule internal/modules/esm/create_dynamic_module',
//       'NativeModule internal/modules/esm/translators',
//       'NativeModule internal/modules/esm/loader',
//       'NativeModule internal/vm/module',
//       'NativeModule internal/process/esm_loader',
//       'NativeModule internal/modules/cjs/loader',
//       'NativeModule internal/modules/run_main',
//       'NativeModule internal/streams/destroy',
//       'NativeModule internal/streams/pipeline',
//       'NativeModule internal/streams/end-of-stream',
//       'NativeModule internal/streams/legacy',
//       'NativeModule internal/streams/buffer_list',
//       'NativeModule internal/streams/state',
//       'NativeModule internal/streams/readable',
//       'NativeModule internal/streams/writable',
//       'NativeModule internal/streams/duplex',
//       'NativeModule internal/streams/transform',
//       'NativeModule internal/streams/passthrough',
//       'NativeModule stream',
//       'NativeModule internal/net',
//       'Internal Binding uv',
//       'Internal Binding stream_wrap',
//       'Internal Binding tcp_wrap',
//       ... 11 more items
//     ],
//     binding: [Function: binding],
//     _linkedBinding: [Function: _linkedBinding],
//     _events: [Object: null prototype] {
//       newListener: [Function: startListeningIfSignal],
//       removeListener: [Function: stopListeningIfSignal],
//       warning: [Function: onWarning],
//       SIGWINCH: [Function (anonymous)]
//     },
//     _eventsCount: 4,
//     _maxListeners: undefined,
//     domain: null,
//     _exiting: false,
//     config: {
//       target_defaults: {
//         cflags: [],
//         default_configuration: 'Release',
//         defines: [],
//         include_dirs: [],
//         libraries: []
//       },
//       variables: {
//         asan: 0,
//         build_v8_with_gn: false,
//         coverage: false,
//         dcheck_always_on: 0,
//         debug_nghttp2: false,
//         debug_node: false,
//         enable_lto: false,
//         enable_pgo_generate: false,
//         enable_pgo_use: false,
//         error_on_warn: false,
//         force_dynamic_crt: 0,
//         host_arch: 'x64',
//         icu_data_in: '..\\..\\deps\\icu-tmp\\icudt67l.dat',
//         icu_endianness: 'l',
//         icu_gyp_path: 'tools/icu/icu-generic.gyp',
//         icu_path: 'deps/icu-small',
//         icu_small: false,
//         icu_ver_major: '67',
//         is_debug: 0,
//         napi_build_version: '7',
//         nasm_version: '2.14',
//         node_byteorder: 'little',
//         node_debug_lib: false,
//         node_enable_d8: false,
//         node_install_npm: true,
//         node_module_version: 83,
//         node_no_browser_globals: false,
//         node_prefix: '/usr/local',
//         node_release_urlbase: 'https://nodejs.org/download/release/',
//         node_shared: false,
//         node_shared_brotli: false,
//         node_shared_cares: false,
//         node_shared_http_parser: false,
//         node_shared_libuv: false,
//         node_shared_nghttp2: false,
//         node_shared_openssl: false,
//         node_shared_zlib: false,
//         node_tag: '',
//         node_target_type: 'executable',
//         node_use_bundled_v8: true,
//         node_use_dtrace: false,
//         node_use_etw: true,
//         node_use_node_code_cache: true,
//         node_use_node_snapshot: true,
//         node_use_openssl: true,
//         node_use_v8_platform: true,
//         node_with_ltcg: true,
//         node_without_node_options: false,
//         openssl_fips: '',
//         openssl_is_fips: false,
//         ossfuzz: false,
//         shlib_suffix: 'so.83',
//         target_arch: 'x64',
//         v8_enable_31bit_smis_on_64bit_arch: 0,
//         v8_enable_gdbjit: 0,
//         v8_enable_i18n_support: 1,
//         v8_enable_inspector: 1,
//         v8_enable_lite_mode: 0,
//         v8_enable_object_print: 1,
//         v8_enable_pointer_compression: 0,
//         v8_no_strict_aliasing: 1,
//         v8_optimized_debug: 1,
//         v8_promise_internal_field_count: 1,
//         v8_random_seed: 0,
//         v8_trace_maps: 0,
//         v8_use_siphash: 1,
//         want_separate_host_toolset: 0
//       }
//     },
//     dlopen: [Function: dlopen],
//     uptime: [Function: uptime],
//     _getActiveRequests: [Function: _getActiveRequests],
//     _getActiveHandles: [Function: _getActiveHandles],
//     reallyExit: [Function: reallyExit],
//     _kill: [Function: _kill],
//     hrtime: [Function: hrtime] { bigint: [Function: hrtimeBigInt] },
//     cpuUsage: [Function: cpuUsage],
//     resourceUsage: [Function: resourceUsage],
//     memoryUsage: [Function: memoryUsage],
//     kill: [Function: kill],
//     exit: [Function: exit],
//     openStdin: [Function (anonymous)],
//     allowedNodeEnvironmentFlags: [Getter/Setter],
//     assert: [Function: deprecated],
//     features: {
//       inspector: true,
//       debug: false,
//       uv: true,
//       ipv6: true,
//       tls_alpn: true,
//       tls_sni: true,
//       tls_ocsp: true,
//       tls: true,
//       cached_builtins: true
//     },
//     _fatalException: [Function (anonymous)],
//     setUncaughtExceptionCaptureCallback: [Function: setUncaughtExceptionCaptureCallback],
//     hasUncaughtExceptionCaptureCallback: [Function: hasUncaughtExceptionCaptureCallback],
//     emitWarning: [Function: emitWarning],
//     nextTick: [Function: nextTick],
//     _tickCallback: [Function: runNextTicks],
//     _debugProcess: [Function: _debugProcess],
//     _debugEnd: [Function: _debugEnd],
//     _startProfilerIdleNotifier: [Function (anonymous)],
//     _stopProfilerIdleNotifier: [Function (anonymous)],
//     stdout: [Getter],
//     stdin: [Getter],
//     stderr: [Getter],
//     abort: [Function: abort],
//     umask: [Function: wrappedUmask],
//     chdir: [Function: wrappedChdir],
//     cwd: [Function: wrappedCwd],
//     env: {
//       ADSK_3DSMAX_x64_2020: 'D:\\Program Files\\Autodesk\\3ds Max 2020\\',
//       ALLUSERSPROFILE: 'C:\\ProgramData',
//       APPDATA: 'C:\\Users\\10577\\AppData\\Roaming',
//       'asl.log': 'Destination=file',
//       CLASSPATH: '.;C:\\Program Files\\Java\\jdk1.8.0_201\\lib\\dt.jar;C:\\Program Files\\Java\\jdk1.8.0_201\\lib\\tools.jar;',
//       CommonProgramFiles: 'C:\\Program Files\\Common Files',
//       'CommonProgramFiles(x86)': 'C:\\Program Files (x86)\\Common Files',
//       CommonProgramW6432: 'C:\\Program Files\\Common Files',
//       COMPUTERNAME: 'TIAOTIAO',
//       ComSpec: 'C:\\Windows\\system32\\cmd.exe',
//       DriverData: 'C:\\Windows\\System32\\Drivers\\DriverData',
//       FPS_BROWSER_APP_PROFILE_STRING: 'Internet Explorer',
//       FPS_BROWSER_USER_PROFILE_STRING: 'Default',
//       HOMEDRIVE: 'C:',
//       HOMEPATH: '\\Users\\10577',
//       JAVA_HOME: 'C:\\Program Files\\Java\\jdk1.8.0_201',
//       LOCALAPPDATA: 'C:\\Users\\10577\\AppData\\Local',
//       LOGONSERVER: '\\\\TIAOTIAO',
//       NUMBER_OF_PROCESSORS: '12',
//       OneDrive: 'C:\\Users\\10577\\OneDrive',
//       OS: 'Windows_NT',
//       Path: 'C:\\Program Files (x86)\\Common Files\\Oracle\\Java\\javapath;C:\\Program Files (x86)\\Razer\\ChromaBroadcast\\bin;C:\\Program Files\\Razer\\ChromaBroadcast\\bin;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Windows\\System32\\OpenSSH\\;C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\Program Files\\NVIDIA Corporation\\NVIDIA NvDLISR;C:\\Program Files\\Common Files\\Autodesk Shared\\;C:\\Program Files\\Microsoft SQL Server\\120\\Tools\\Binn\\;C:\\Users\\10577\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Program Files\\dotnet\\;D:\\susu\\git\\Git\\cmd;D:\\susu\\nodejs\\;C:\\Program Files\\Java\\jdk1.8.0_201\\bin;C:\\Program Files\\Java\\jdk1.8.0_201\\jre\\bin;C:\\Program Files\\MySQL\\MySQL Server 8.0\\bin;D:\\susu\\py\\py;C:\\Users\\10577\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Users\\10577\\.dotnet\\tools;D:\\susu\\vscode\\Microsoft VS Code\\bin;C:\\Users\\10577\\AppData\\Roaming\\npm',
//       PATHEXT: '.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC',
//       PROCESSOR_ARCHITECTURE: 'AMD64',
//       PROCESSOR_IDENTIFIER: 'Intel64 Family 6 Model 158 Stepping 10, GenuineIntel',
//       PROCESSOR_LEVEL: '6',
//       PROCESSOR_REVISION: '9e0a',
//       ProgramData: 'C:\\ProgramData',
//       ProgramFiles: 'C:\\Program Files',
//       'ProgramFiles(x86)': 'C:\\Program Files (x86)',
//       ProgramW6432: 'C:\\Program Files',
//       PROMPT: '$P$G',
//       PSModulePath: 'C:\\Program Files\\WindowsPowerShell\\Modules;C:\\Windows\\system32\\WindowsPowerShell\\v1.0\\Modules',
//       PUBLIC: 'C:\\Users\\Public',
//       SESSIONNAME: 'Console',
//       SystemDrive: 'C:',
//       SystemRoot: 'C:\\Windows',
//       TEMP: 'C:\\Users\\10577\\AppData\\Local\\Temp',
//       TMP: 'C:\\Users\\10577\\AppData\\Local\\Temp',
//       USERDOMAIN: 'TIAOTIAO',
//       USERDOMAIN_ROAMINGPROFILE: 'TIAOTIAO',
//       USERNAME: 'HZL',
//       USERPROFILE: 'C:\\Users\\10577',
//       windir: 'C:\\Windows',
//       WXDRIVE_START_ARGS: '--wxdrive-setting=0 --disable-gpu --disable-software-rasterizer --enable-features=NetworkServiceInProcess',
//       ZES_ENABLE_SYSMAN: '1'
//     },
//     title: 'C:\\Windows\\System32\\cmd.exe - node  process.js',
//     argv: [
//       'D:\\susu\\nodejs\\node.exe',
//       'C:\\Users\\10577\\Desktop\\su-sus-vue\\vue_demo\\src\\process\\process.js'
//     ],
//     execArgv: [],
//     pid: 6968,
//     ppid: 1808,
//     execPath: 'D:\\susu\\nodejs\\node.exe',
//     debugPort: 9229,
//     argv0: 'node',
//     _preload_modules: [],
//     mainModule: Module {
//       id: '.',
//       path: 'C:\\Users\\10577\\Desktop\\su-sus-vue\\vue_demo\\src\\process',
//       exports: {},
//       parent: null,
//       filename: 'C:\\Users\\10577\\Desktop\\su-sus-vue\\vue_demo\\src\\process\\process.js',
//       loaded: false,
//       children: [],
//       paths: [
//         'C:\\Users\\10577\\Desktop\\su-sus-vue\\vue_demo\\src\\process\\node_modules',
//         'C:\\Users\\10577\\Desktop\\su-sus-vue\\vue_demo\\src\\node_modules',
//         'C:\\Users\\10577\\Desktop\\su-sus-vue\\vue_demo\\node_modules',
//         'C:\\Users\\10577\\Desktop\\su-sus-vue\\node_modules',
//         'C:\\Users\\10577\\Desktop\\node_modules',
//         'C:\\Users\\10577\\node_modules',
//         'C:\\Users\\node_modules',
//         'C:\\node_modules'
//       ]
//     },
//     [Symbol(kCapture)]: false
//   }


// process.env属性返回的是一个包含用户环境信息的对象，它可以区分开发环境或正式环境的依据